services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: >
      start-dev 
      --spi-theme-cache-themes=false 
      --spi-theme-cache-templates=false
      --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./realms/import/poupe-ai-realm.json:/opt/keycloak/data/import/poupe-ai-realm.json
      - ./themes:/opt/keycloak/themes
    depends_on:
      - postgres
    networks:
      - poupeai-network

  postgres:
    image: postgres:latest
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poupeai-network

volumes:
  postgres_data:
    driver: local

networks:
  poupeai-network:
    driver: bridge 