_format_version: "3.0"
_transform: true

services:
  - name: finances-service
    url: http://finances-service:8000
    routes:
      - name: finances-all-routes
        paths:
          - /finances
        strip_path: true
        methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
    plugins:
      - name: jwt
        config:
          key_claim_name: iss
          claims_to_verify:
            - exp
      - name: jwt-header-injector

  - name: reports-service
    url: http://reports-service:5000
    routes:
      - name: reports-all-routes
        paths:
          - /reports
        strip_path: true
        methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
    plugins:
      - name: jwt
        config:
          key_claim_name: iss
          claims_to_verify:
            - exp
      - name: jwt-header-injector

consumers:
  - username: keycloak-consumer
    jwt_secrets:
      - key: http://localhost:8080/realms/poupe-ai
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt2+ZGjEof6HNQLK2M71E
          Mx00+dS5cp8C84EW29TTLUtqygr1MvIMFrQRfWuF8D/IVeTsMJIgZqgNqkwFE1L9
          lLJ93LzXg6iv4GrYfQEGU3s44woHQtdBPsjKr0QYa8BeGS+KxmwxSbBx1WGZP0ON
          ST4Qy9VsIMP4vkxdtxv97xKm0LOjgu/UfiTbwEb9ZTUeg66YVvo7UXPDbsYPAITc
          h8kcD6JoOERebfbbYi57YyhFWHHqZgi3srDbtFc7eTIwt+DyxbI2mmwdSg4qSEG/
          2SrAfwGPW6YFnZ5+ocVGq0OhfDli0YI7yJgucZ0Lsbw12rn5WeIMnvGr+K7oS5wK
          EwIDAQAB
          -----END PUBLIC KEY-----

plugins:
  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid